name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release package

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build & pack the library
        run: pnpm pack

      - name: Publish to npm
        run: pnpm publish
